spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #애플리케이션 실행시 가지고 있는 테이블을 모두 지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true //시스템아웃에 찍힘
       format_sql: true


logging:
  level:
    org.hibernate.SQL: debug #로그에 찍힘

server:
  port: 8081


